### ISSUE TITLE
iterator_facade compilation error with Visual Studio 2019 16.9.0 Preview 3

### ISSUE THREAD

**Issue by AlexBAV** [vector-of-bool/neo-fun#1]
Hi!

I've just upgraded to the latest Visual Studio Preview and started getting compilation errors. I narrowed down the problem in the following code snippet:

https://godbolt.org/z/P4ThTr

Originally I thought there was an error with the latest Preview, but decided to check with clang. clang produces a warning saying "This is ambiguous per C++20 rules blah blah blah". Apparently what they mark as warning is promoted to the error in latest VS Preview.

I've asked a question on stackoverflow.com and wanted to let you know. Is it possible that you know the solution to this problem? If it is not a bug with Visual C++ (and by clang's behavior I think it is not a bug), it looks like `iterator_facade` becomes totally broken. Is it at all possible to make a synthesized comparison operators standard compliant?

https://stackoverflow.com/questions/65833022/inherited-synthesized-comparison-operator-produces-warning-error-iso-c20-cons

**Comment by vector-of-bool** [comment]
Thanks! This is a very helpful SO question+answer. TIL. @brevzin is probably correct that this could be changed to remove the `equal_to` design and just expect derived classes provide their own `operator==` now that I'm already relying on C++20 support.

**Comment by AlexBAV** [comment]
> Thanks! This is a very helpful SO question+answer. TIL. @BRevzin is probably correct that this could be changed to remove the `equal_to` design and just expect derived classes provide their own `operator==` now that I'm already relying on C++20 support.

I also think this might be the right thing to do. You only lose the possibility to reuse `distance_to`, but maybe this would result in better code gen.

**Comment by vector-of-bool** [comment]
This is fixed in 0.7.2, and we simply no longer synthesize _any_ `operator==`. This means users must provide `operator==` for any sentinel type, including sized sentinels that we _could have_ inferred from `distance_to()` (I could find no way to make such inference work).
